# Building GPT From Scratch

[Let's build GPT: from scratch, in code, spelled out](https://www.youtube.com/watch?v=kCc8FmEb1nY&t=11s)

| Date | User | Change Type | Remarks |  
| ---- | ---- | ----------- | ------- |
| 05/11/2025   | Martin | Created   | Notebook created to build GPT from scratch | 

# Content

* [Load Data](#load-data)

In [4]:
%load_ext watermark

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark


In [5]:
import pandas as pd
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch

# Load Data

Using the Tiny Shakespeare dataset found [here](https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt).

Training a model on Shakespeare's text to predict the next character given a prompt.

In [6]:
with open('data/shakespeare.txt', 'r') as f:
  text = f.read()

In [7]:
print(f"Length of dataset in chraceters: {len(text)}")

Length of dataset in chraceters: 1115394


In [8]:
# First thousand characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [9]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(f"Number of unique chracters: {vocab_size}")


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
Number of unique chracters: 65


In [10]:
# Create mappers 
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda x: [stoi[c] for c in x] # Convert strings to index
decode = lambda x: ''.join([itos[c] for c in x]) # Convert index to strings

Convert entire text into indexes, then split into train and test

In [11]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [12]:
sp = 0.9
idx = int(sp * len(data))
train_data = data[:idx]
val_data = data[idx:]

Each sequence of letters are training data is actually multiple training instances. The context length grows from the shortest length predicting every next letter till the full sequence of letters is formed

In [13]:
block_size = 8
x = train_data[:8]
y = train_data[1:8+1]
for t in range(block_size):
  inp = x[:t+1]
  out = y[t]
  print(f"When input is {inp}, the target is {out}")

When input is tensor([18]), the target is 47
When input is tensor([18, 47]), the target is 56
When input is tensor([18, 47, 56]), the target is 57
When input is tensor([18, 47, 56, 57]), the target is 58
When input is tensor([18, 47, 56, 57, 58]), the target is 1
When input is tensor([18, 47, 56, 57, 58,  1]), the target is 15
When input is tensor([18, 47, 56, 57, 58,  1, 15]), the target is 47
When input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), the target is 58


In [14]:
# Creating minibatch
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
  data = train_data if split == 'train' else val_data
  idx = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([train_data[i:i+block_size] for i in idx])
  y = torch.stack([train_data[i+1:i+1+block_size] for i in idx])
  return x, y

X_batch, y_batch = get_batch("train")
print("inputs:")
print(X_batch.shape)
print(X_batch)
print("outputs:")
print(y_batch.shape)
print(y_batch)

print("----")

for b in range(batch_size):
  for t in range(block_size):
    context = X_batch[b, :t+1]
    target = y_batch[b, t]
    print(f"When input is {context.tolist()}, the target is {target}")
  print()

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
outputs:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
When input is [24], the target is 43
When input is [24, 43], the target is 58
When input is [24, 43, 58], the target is 5
When input is [24, 43, 58, 5], the target is 57
When input is [24, 43, 58, 5, 57], the target is 1
When input is [24, 43, 58, 5, 57, 1], the target is 46
When input is [24, 43, 58, 5, 57, 1, 46], the target is 43
When input is [24, 43, 58, 5, 57, 1, 46, 43], the target is 39

When input is [44], the target is 53
When input is [44, 53], the target is 56
When input is [44, 53, 56], the target is 1
When input is [44, 53, 56, 1], the target is 58
When input is [44, 53, 56, 1, 58]

---

# Bigram Model

In [42]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

In [112]:
class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    # Each token directly reads off the logits for the next token from a lookup table
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

  def forward(self, idx, targets=None):
    # B - batch size
    # T - time (similar to tracking which set of text has been seen)
    # C - embedding size
    logits = self.token_embedding_table(idx)

    # Reshape the logits tensor to match those used by cross entropy
    if targets == None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)

      loss = F.cross_entropy(logits, targets)
    return logits, loss
  
  def generate(self, idx, max_new_tokens):
    # idx is (B, T) array of indices in the current context
    for _ in range(max_new_tokens):
      # get the predictions
      logits, loss = self(idx)
      # focus on the last time step
      logits = logits[:, -1, :]
      # apply softmax to get probabilities
      probs = F.softmax(logits, dim=1)
      # sample from the distribution
      idx_next = torch.multinomial(probs, num_samples=1)
      # append the sampled index to the existing sequence
      idx = torch.cat((idx, idx_next), dim=1)
    return idx

In [113]:
m = BigramLanguageModel(vocab_size)
logits, loss = m(X_batch, y_batch)
print(logits.shape)
print(loss)

torch.Size([32, 65])
tensor(4.8380, grad_fn=<NllLossBackward0>)


In [117]:
starting_idx = torch.zeros((1, 1), dtype=torch.long)
print(decode(m.generate(starting_idx, max_new_tokens=100)[0].tolist()))


C'DOKwZrFmsRw?VlCzbkKFlrchHi.zvYdwI.UcMjF&TmtHXUxP
AYJ'&:;z,TpuuN&3V
kHC,BaT&o.JVbmwLEMqkpROwUTBCFH3


Create a Pytorch optimiser (usually for Adam, lr=1e-4 to 1e-3)

In [121]:
# create a PyTorch optimiser
optimiser = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [124]:
# Training loop
batch_size = 32
for _ in range(100000):
  X_batch, y_batch = get_batch('train')

  optimiser.zero_grad(set_to_none=True)
  logits, loss = m(X_batch, y_batch)

  loss.backward()
  optimiser.step()

print(loss.item())

2.505732297897339


In [127]:
print(decode(m.generate(starting_idx, max_new_tokens=100)[0].tolist()))



Thens, he avel dsicoy bint Tecammearof ake? Shey be e hsat D himalintilfede e:
Wine ge ry.
ithe fea


In [ ]:
%watermark